# .docker/docker-compose-dev-hot.yml

services:
  web:
    image: ${ORGANIZATION}/codeblox-dev
    container_name: codeblox-nextjs-devhot
    ports:
      - "3000:3000"
    volumes:
      - ../:/usr/src/app:cached  # Mount the application code for hot reloading
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000  # Adjust polling interval for better performance (optional)
    command: bash -c "npm install && npm run dev:hot"  # Install dependencies and start the dev server
    depends_on:
      - postgres-db-test
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]  # Healthcheck to ensure the app is running
      interval: 30s
      timeout: 10s
      retries: 5

  postgres-db-test:
    build:
      context: ..
      dockerfile: .docker/Dockerfile-postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - test-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  test-db-volume: