# path:  .docker/docker-compose-postgres.dev.yml

services:
  postgres-db:
    image: ${ORGANIZATION}/codeblox-dev-postgres
    env_file:
      - ../.configs/.env.development
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - test-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      default:
        aliases:
          - ${POSTGRES_HOST_ALIAS}


volumes:
  test-db-volume: